### ISSUE TITLE
What's a "Hero image"?

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/project-iamus-dashboard#10]
Is it just a large image? ("Hero image" isn't a term I'm familiar with.)

**Comment by kasenvr** [comment]
I hope the placeholder text helps explain that a bit more. "Large Sized Image"

**Comment by ctrlaltdavid** [comment]
It does, thank you.

**Comment by kasenvr** [comment]
Oh and one more thing, if you put a URL in, you can preview the image by clicking the left icons for the images. :) Working on getting tooltips in though.
