### ISSUE TITLE
Cannot delete domains

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/project-iamus-dashboard#17]
I have a bunch of old domains listed in https://dashboard.vircadia.com/domain that I want to delete.
The trashcan icons are red (indicating that I should have permission to delete the domains).
Clicking a trashcan icon displays an "are you sure?" dialog.
OKing this dialog closes it but the domain isn't deleted.
In the browser console, errors are reported after clicking "OK":

[delete-domain-error.log](https://github.com/vircadia/project-iamus-dashboard/files/5294720/delete-domain-error.log)

**Comment by kasenvr** [comment]
I believe Mr. Blue assigned himself to this issue as Vegaslon confirmed that it's hardcoded to only allow admins to delete, it should be fixed in the latest version (2.2.8) of Iamus. https://github.com/kasenvr/Iamus/commit/7c5f03c

**Comment by ctrlaltdavid** [comment]
Confirmed fixed in 2.2.8.
