### ISSUE TITLE
Font looks weird on login screen

### ISSUE THREAD

**Issue by JulianGro** [vircadia/project-iamus-dashboard#20]
The font on the login screen looks very weird when it is prefilled by the browser. Maybe it is set to be too small? The size changes when the text box is focused.

![2020-10-01 04 04 36 dashboard vircadia com 0de04a65a2bd](https://user-images.githubusercontent.com/11144627/94757739-799bcd00-039b-11eb-9ee4-06e7b55aa1cb.png)

**Comment by SilverfishVR** [comment]
same for me in chrome on a 3440x1440 resolution, but really a minor issue

**Comment by JulianGro** [comment]
This was on Vivaldi on Linux Mint 19.3. Firefox looks perfectly fine.
This is only when the fields are pre-filled by the webbrowser. It works fine for Kalila on Chrome on Windows. Potentially it is a resolution thing? Kalila uses a 1080p screen, while I use a 1440p screen.
It looks fine on Firefox: 
![1Auswahl_770](https://user-images.githubusercontent.com/11144627/95516968-694da880-09c0-11eb-8f88-0e2a3abd5328.png)

**Comment by digisomni** [comment]
Is this still an issue?

**Comment by JulianGro** [comment]
Doesn't seem to appear anymore. I would assume it has been fixed in Chromium.
