### ISSUE TITLE
Cannot change username

### ISSUE THREAD

**Issue by JulianGro** [vircadia/project-iamus-dashboard#21]
Cannot change username from ``motofckr9k`` to ``MotoFckr9k``

![2020-10-01 04 05 44 dashboard vircadia com 69b671904e55](https://user-images.githubusercontent.com/11144627/94757830-b1a31000-039b-11eb-8f63-de2a7c0a4fae.png)

**Comment by Misterblue** [comment]
This is a problem in Iamus where the setting permissions didn't allow the change of the username field. Changing the username is problematic, though, as the username is used as a unique handle to an account and it could be cached in scripts, friends lists, etc.

But, the latest changes to Iamus should allow a user to change their own username.

**Comment by digisomni** [comment]
I believe this was fixed, we can reopen the issue if this still happens.

**Comment by JulianGro** [comment]
It does indeed work now.
