### ISSUE TITLE
Domain access token should be easier to add to clipboard

### ISSUE THREAD

**Issue by JulianGro** [vircadia/project-iamus-dashboard#22]
When creating a domain access token, it kind of just sits there. It should have a "copy to clipboard" button like other modern websites.

![2020-10-01 11 26 09 dashboard vircadia com c295120d18c2](https://user-images.githubusercontent.com/11144627/94792328-1cbf0780-03d9-11eb-88fc-d6bdaf3f793e.png)

**Comment by kasenvr** [comment]
Completed with v1.0.0 release.
