### ISSUE TITLE
Tokens are case sensitive so the "Register domain" dialog showing in upper case is bad

### ISSUE THREAD

**Issue by Misterblue** [vircadia/project-iamus-dashboard#24]
The "Register domain" dialog displays the created domain access token in all upper-case. If copied with the "copy to clipboard" button, the original (lower-case) version is put in the clipboard but using the mouse to select the displayed token text and doing cntl-C, copies an upper-case'ified version of the domain token.

The token should be displayed in its original, non-case-changed form.

**Comment by kasenvr** [comment]
Missed this one, will tackle it next. :)

**Comment by kasenvr** [comment]
Fixed with version 1.1.1.
