### ISSUE TITLE
Domain setup initial name dialog does not report errors if name is bad format

### ISSUE THREAD

**Issue by Misterblue** [vircadia/project-iamus-dashboard#25]
When doing initial domain setup, after creating the domain access token and pasting it in the dialog, the domain name dialog pops up. If one enters a bad domain name (with spaces or special characters), the request to the metavere-server fails, does not create the domain and the user is left back at  the "Connect account ..." setup page with no indication of an error.

It would also be good to add text to that dialog to say that the domain name must be alpha-numeric plus "+-_".

**Comment by kasenvr** [comment]
This seems like an issue for the project-athena repo. :)

**Comment by Misterblue** [comment]
I don't have the permissions to transfer this issue. Feel free to transfer it to that project.
