### ISSUE TITLE
Error when opening dashboard.vircadia.com without metaverse specified

### ISSUE THREAD

**Issue by JulianGro** [vircadia/project-iamus-dashboard#5]
When creating an account on https://dashboard.vircadia.com/?metaverse=https://metaverse.bluestuff.org:9400 and then opening https://dashboard.vircadia.com/ I get an error (presumably because they are different metaverse servers)
![1Auswahl_753](https://user-images.githubusercontent.com/11144627/93687247-6431c380-fabc-11ea-8566-cb4fe50ae3fa.png)

**Comment by kasenvr** [comment]
This has been fixed with version 0.0.1b which is live. :)
